import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/listing_model.dart';
import '../utils/constants.dart';

/// Service layer handling all Cloud Firestore CRUD operations for listings.
///
/// No UI widget should call Firestore directly. All database interactions are
/// routed through this service, which is consumed by [ListingsProvider].
class FirestoreService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Reference to the listings collection.
  CollectionReference get _listingsRef =>
      _firestore.collection(AppConstants.listingsCollection);

  // ═══════════════════════════════════════════════════════════════════════════
  // REAL-TIME STREAMS
  // ═══════════════════════════════════════════════════════════════════════════

  /// Returns a real-time stream of ALL listings, ordered by creation date
  /// (newest first). The Directory screen listens to this stream.
  Stream<List<ListingModel>> getListingsStream() {
    return _listingsRef
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ListingModel.fromFirestore(doc))
            .toList());
  }

  /// Returns a real-time stream of listings created by [userId].
  /// The My Listings screen listens to this stream.
  Stream<List<ListingModel>> getUserListingsStream(String userId) {
    return _listingsRef
        .where('createdBy', isEqualTo: userId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ListingModel.fromFirestore(doc))
            .toList());
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATE
  // ═══════════════════════════════════════════════════════════════════════════

  /// Creates a new listing document in Firestore.
  ///
  /// The document ID is auto-generated by Firestore.
  /// Returns the generated document ID.
  Future<String> createListing(ListingModel listing) async {
    final docRef = await _listingsRef.add(listing.toFirestore());
    return docRef.id;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // READ (single document)
  // ═══════════════════════════════════════════════════════════════════════════

  /// Retrieves a single listing by its document [id].
  Future<ListingModel?> getListingById(String id) async {
    final doc = await _listingsRef.doc(id).get();
    if (doc.exists) {
      return ListingModel.fromFirestore(doc);
    }
    return null;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // UPDATE
  // ═══════════════════════════════════════════════════════════════════════════

  /// Updates an existing listing identified by [listing.id].
  ///
  /// Only the fields present in the model are overwritten.
  Future<void> updateListing(ListingModel listing) async {
    await _listingsRef.doc(listing.id).update({
      'name': listing.name,
      'category': listing.category,
      'address': listing.address,
      'contactNumber': listing.contactNumber,
      'description': listing.description,
      'latitude': listing.latitude,
      'longitude': listing.longitude,
      'updatedAt': Timestamp.fromDate(DateTime.now()),
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // DELETE
  // ═══════════════════════════════════════════════════════════════════════════

  /// Deletes the listing document with the given [id].
  Future<void> deleteListing(String id) async {
    await _listingsRef.doc(id).delete();
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // SEED DATA
  // ═══════════════════════════════════════════════════════════════════════════

  /// Seeds the Firestore database with sample Kigali listings.
  ///
  /// This is a utility method intended for initial setup and testing.
  /// Pass the [userId] of the authenticated user who will own these listings.
  Future<void> seedSampleListings(String userId) async {
    final now = DateTime.now();
    final sampleListings = [
      ListingModel(
        id: '',
        name: 'King Faisal Hospital',
        category: 'Hospital',
        address: 'KG 544 St, Kigali',
        contactNumber: '+250 788 305 087',
        description:
            'One of the largest referral hospitals in Rwanda, offering specialized medical services including surgery, internal medicine, pediatrics, and emergency care.',
        latitude: -1.9474,
        longitude: 29.8585,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Kigali Serena Hotel',
        category: 'Restaurant',
        address: 'KN 3 Ave, Kigali',
        contactNumber: '+250 252 597 100',
        description:
            'A luxury five-star hotel featuring multiple dining options including The Milima Restaurant, offering international and Rwandan cuisine in an elegant setting.',
        latitude: -1.9540,
        longitude: 29.8565,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Inema Art Center',
        category: 'Tourist Attraction',
        address: 'KG 563 St, Kacyiru, Kigali',
        contactNumber: '+250 788 310 325',
        description:
            'A vibrant contemporary art center showcasing local Rwandan artists. Features galleries, workshops, live painting sessions, and a beautiful garden café.',
        latitude: -1.9386,
        longitude: 29.8600,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Kigali Public Library',
        category: 'Library',
        address: 'KN 4 Ave, Kigali',
        contactNumber: '+250 252 573 623',
        description:
            'The main public library of Kigali offering a large collection of books, periodicals, and digital resources. Features reading rooms, study areas, and community programs.',
        latitude: -1.9510,
        longitude: 29.8620,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Remera Police Station',
        category: 'Police Station',
        address: 'KG 11 Ave, Remera, Kigali',
        contactNumber: '+250 788 311 155',
        description:
            'Remera district police station providing public safety services, community policing, crime reporting, and emergency response for the Remera area.',
        latitude: -1.9527,
        longitude: 29.8810,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Question Coffee',
        category: 'Café',
        address: 'KN 43 St, Kiyovu, Kigali',
        contactNumber: '+250 788 428 380',
        description:
            'A specialty coffee shop that supports women cooperatives in Rwanda. Known for single-origin Rwandan coffee, artisan pastries, and a cozy atmosphere.',
        latitude: -1.9585,
        longitude: 29.8540,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Nyamirambo Women\'s Center',
        category: 'Tourist Attraction',
        address: 'KN 85 St, Nyamirambo, Kigali',
        contactNumber: '+250 788 721 828',
        description:
            'A community center offering walking tours through the vibrant Nyamirambo neighborhood, Rwandan cooking classes, and cultural experiences led by local women.',
        latitude: -1.9745,
        longitude: 29.8445,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Kigali Convention Centre',
        category: 'Tourist Attraction',
        address: 'KG 2 Roundabout, Kimihurura, Kigali',
        contactNumber: '+250 252 252 252',
        description:
            'An iconic dome-shaped convention center and one of Kigali\'s most recognizable landmarks. Hosts conferences, exhibitions, and cultural events.',
        latitude: -1.9490,
        longitude: 29.8740,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Bourbon Coffee Kiyovu',
        category: 'Café',
        address: 'KN 27 St, Kiyovu, Kigali',
        contactNumber: '+250 788 303 041',
        description:
            'A popular Rwandan coffee chain serving premium locally-sourced coffee, smoothies, sandwiches, and pastries. A great spot for remote work or casual meetings.',
        latitude: -1.9560,
        longitude: 29.8555,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
      ListingModel(
        id: '',
        name: 'Simba Supermarket',
        category: 'Utility Office',
        address: 'KN 82 St, Remera, Kigali',
        contactNumber: '+250 788 186 400',
        description:
            'One of the largest supermarkets in Kigali offering groceries, household items, electronics, and imported goods. Convenient for everyday shopping needs.',
        latitude: -1.9530,
        longitude: 29.8800,
        createdBy: userId,
        createdAt: now,
        updatedAt: now,
      ),
    ];

    final batch = _firestore.batch();
    for (final listing in sampleListings) {
      final docRef = _listingsRef.doc();
      batch.set(docRef, listing.toFirestore());
    }
    await batch.commit();
  }
}
