// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZy-kzCHfokfWehjbbM1waJAtB0Ejdf0',
    appId: '1:913346961662:android:ec40bef2ecdf3781ea05af',
    messagingSenderId: '913346961662',
    projectId: 'kigali-directory-faf31',
    storageBucket: 'kigali-directory-faf31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxG3YPQYDg9N4aZriU8wiBccdirzetB7E',
    appId: '1:913346961662:ios:ab53883b34efd791ea05af',
    messagingSenderId: '913346961662',
    projectId: 'kigali-directory-faf31',
    storageBucket: 'kigali-directory-faf31.firebasestorage.app',
    iosBundleId: 'com.example.kigalidirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxG3YPQYDg9N4aZriU8wiBccdirzetB7E',
    appId: '1:913346961662:ios:ab53883b34efd791ea05af',
    messagingSenderId: '913346961662',
    projectId: 'kigali-directory-faf31',
    storageBucket: 'kigali-directory-faf31.firebasestorage.app',
    iosBundleId: 'com.example.kigalidirectory',
  );
}
